const ApiRoutes = {
    auth: {
        login: "/api/v1/users/login",
        googleLogin: "/api/v1/users/google-login",
        register: "/api/v1/users/register",
        forgotPassword: "/api/v1/users/forgot-password",
        resetPassword: "/api/v1/users/reset-password",
        logout: "/api/v1/users/logout",
    },
    email: {
        sendVerification: "/api/v1/email/send-verification",
        verify: "/api/v1/email/verify",
        resendVerification: "/api/v1/email/resend-verification",
    },
    user: {
        getUser: "/api/v1/users/user",
        updateUser: "/api/v1/users/user",
        refreshToken: "/api/v1/users/refresh-token",
        checkAuth: "/api/v1/users/check-auth",
    },
    problems: {
        create: "/api/v1/problems",
        getAll: "/api/v1/problems",
        getMy: "/api/v1/problems/my-problems",
        getById: (id) => `/api/v1/problems/${id}`,
        update: (id) => `/api/v1/problems/${id}`,
        delete: (id) => `/api/v1/problems/${id}`,
        submit: (id) => `/api/v1/problems/${id}/submit`,
        getSubmissions: (id) => `/api/v1/problems/${id}/submissions`,
    },
    compiler: {
        execute: "/api/v1/compiler/execute",
        executeTests: "/api/v1/compiler/execute-tests",
        languages: "/api/v1/compiler/languages",
    },
    ai: {
        reviewCode: "/api/v1/ai/review-code",
    },
    quizzes: {
        getAll: "/api/v1/quizzes",
        getById: (id) => `/api/v1/quizzes/${id}`,
        submit: "/api/v1/quizzes/submit",
        getUserSubmissions: "/api/v1/quizzes/submissions",
        analytics: "/api/v1/quizzes/analytics",
        getReport: (submissionId) => `/api/v1/quizzes/report/${submissionId}`,
        downloadPDF: (submissionId) => `/api/v1/quizzes/report/${submissionId}/pdf`,
        downloadCertificate: (submissionId) => `/api/v1/quizzes/certificate/${submissionId}`,
        debugSubmissions: "/api/v1/quizzes/debug/submissions",
    },
    resumeAI: {
        health: "/api/v1/resume-ai/health",
        getRoles: "/api/v1/resume-ai/roles",
        getTemplates: "/api/v1/resume-ai/templates",
        analyze: "/api/v1/resume-ai/analyze",
        create: "/api/v1/resume-ai/create",
        askQuestion: (sessionId) => `/api/v1/resume-ai/ask-question/${sessionId}`,
        generateInterviewQuestions: (sessionId) => `/api/v1/resume-ai/generate-interview-questions/${sessionId}`,
        improveResume: (sessionId) => `/api/v1/resume-ai/improve-resume/${sessionId}`,
        getImprovedResume: (sessionId) => `/api/v1/resume-ai/get-improved-resume/${sessionId}`,
        saveImprovedResume: (sessionId) => `/api/v1/resume-ai/save-improved-resume/${sessionId}`,
        getAnalysis: (sessionId) => `/api/v1/resume-ai/analysis/${sessionId}`,
        restoreSession: (sessionId) => `/api/v1/resume-ai/restore-session/${sessionId}`,
        getHistory: "/api/v1/resume-ai/history",
        getCreatedResumes: "/api/v1/resume-ai/created-resumes",
        cleanupSession: (sessionId) => `/api/v1/resume-ai/session/${sessionId}`,
    },
    internships: {
        getAll: "/api/v1/internships",
        getById: (id) => `/api/v1/internships/${id}`,
        enroll: (id) => `/api/v1/internships/${id}/enroll`,
        getEnrolled: "/api/v1/internships/user/enrollments",
        submit: "/api/v1/internships/submissions",
        getSubmission: (enrollmentId) => `/api/v1/internships/submissions/${enrollmentId}`,
        getPendingSubmissions: "/api/v1/internships/admin/submissions",
        approveSubmission: (id) => `/api/v1/internships/admin/submissions/${id}/approve`,
        rejectSubmission: (id) => `/api/v1/internships/admin/submissions/${id}/reject`,
        create: "/api/v1/internships",
        update: (id) => `/api/v1/internships/${id}`,
        delete: (id) => `/api/v1/internships/${id}`,
        downloadOfferLetter: (enrollmentId) => `/api/v1/internships/enrollments/${enrollmentId}/offer-letter`,
        downloadCertificate: (submissionId) => `/api/v1/internships/certificates/${submissionId}`,
    },
    subscription: {
        current: "/api/v1/subscription/current",
        plans: "/api/v1/subscription/plans",
        upgrade: "/api/v1/subscription/upgrade",
        cancel: "/api/v1/subscription/cancel",
        aiUsage: "/api/v1/subscription/ai-usage"
    },
    interview: {
        start: "/api/v1/interview/start",
        question: "/api/v1/interview/question",
        answer: "/api/v1/interview/answer",
        followupAnswer: "/api/v1/interview/followup-answer",
        report: "/api/v1/interview/report",
        status: (sessionId) => `/api/v1/interview/status/${sessionId}`,
        history: "/api/v1/interview/history",
        shared: (shareToken) => `/api/v1/interview/shared/${shareToken}`,
        tts: "/api/v1/interview/tts",
        stt: "/api/v1/interview/stt",
        completeRound: "/api/v1/interview/complete-round",
        myInterviews: "/api/v1/interview/my-interviews",
        details: (sessionId) => `/api/v1/interview/details/${sessionId}`,
        delete: (sessionId) => `/api/v1/interview/${sessionId}`,
    }
};

export default ApiRoutes;
